name: homipro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/Images/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "Assets/Images/logo.jpg"
    background_color: "#ffffff"
    theme_color: "#2C6DB5"
  windows:
    generate: true
    image_path: "Assets/Images/logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "Assets/Images/logo.jpg"
